export const {
  REACT_APP_SERVER_BASE_URL,
  REACT_APP_SERVER_CLOUD_URL,
  REACT_APP_SERVER_MISA_BASE_URL,
  REACT_APP_TELEGRAM_BOT,
  REACT_APP_TELEGRAM_API_BOT,
} = process.env || {};

export const AIPT_WEB_TOKEN = "AIPT_WEB_DBMS_TOKEN";
